In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.2'

# Numpy的聚合操作

In [4]:
L = np.random.random(100)
L

array([0.68443779, 0.08067137, 0.60872892, 0.39408114, 0.1726906 ,
       0.47133707, 0.76811942, 0.91907564, 0.8693991 , 0.44183741,
       0.39790671, 0.93034495, 0.94661853, 0.84437917, 0.62108519,
       0.87262204, 0.9393922 , 0.3254859 , 0.41878907, 0.05012337,
       0.66348077, 0.132057  , 0.02553844, 0.53484969, 0.5318548 ,
       0.78376017, 0.00912867, 0.24957735, 0.54981696, 0.96715103,
       0.7475215 , 0.24456858, 0.8606832 , 0.66715726, 0.5338388 ,
       0.82897771, 0.02742821, 0.90426594, 0.22782823, 0.48047337,
       0.16794626, 0.70356577, 0.71049752, 0.58815024, 0.20791341,
       0.26016852, 0.35701796, 0.2270099 , 0.5985486 , 0.09580226,
       0.56223433, 0.37266267, 0.27733954, 0.54939628, 0.98281592,
       0.88739402, 0.88356768, 0.07856609, 0.22266597, 0.13675913,
       0.49829037, 0.74823922, 0.5011235 , 0.90649355, 0.15964146,
       0.85174464, 0.63976539, 0.85895604, 0.8920102 , 0.81319427,
       0.53274653, 0.54355437, 0.74419742, 0.28484113, 0.01358

-python 中求和

- python中求和

In [5]:
sum(L)

53.10875179542886

In [6]:
np.sum(L)

53.108751795428844

In [7]:
np.random.rand(1000000)

array([0.36310671, 0.13651548, 0.86181694, ..., 0.95694179, 0.35990933,
       0.34598321])

In [8]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

85.2 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


410 µs ± 7.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
np.min(big_array)

4.269603969264679e-07

In [10]:
np.max(big_array)

0.9999995532329816

# 面向对象的书写方式

In [11]:
big_array.min()

4.269603969264679e-07

In [12]:
big_array.max()

0.9999995532329816

In [13]:
big_array.sum()

499959.6153099939

# 多维度聚合

In [15]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.sum(X)

120

In [18]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [19]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

# 其他的聚合操作

- 所有元素乘积

In [21]:
np.prod(X)

0

In [22]:
np.prod(X+1)

20922789888000

- 平均值

In [24]:
np.mean(X)

7.5

In [25]:
np.median(X)

7.5

In [26]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [27]:
np.median(v)

2.0

In [28]:
np.percentile(v, q=50)

2.0

In [29]:
np.percentile(v, q=25)

1.0

In [30]:
np.percentile(v, q=100)

10.0

In [31]:
np.percentile(v, q=75)

2.0

In [32]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent ))

4.269603969264679e-07
0.2500431850827415
0.5001591173129294
0.7497940206846287
0.9999995532329816


In [34]:
np.var(big_array)

0.08330995375415622

In [35]:
np.std(big_array)

0.2886346371351786

In [36]:
x = np.random.normal(0, 1, 1000000)

In [37]:
np.mean(x)

0.0009193070254655604

In [38]:
np.std(x)

1.0006998214034255