# numpy中的矩阵运算

In [1]:
import numpy as np

In [2]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []
for e in L:
    A.append(e*2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
%%time
A = []
for e in L:
    A.append(e*2)

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 11 µs


In [6]:
%%time
A = [i*2 for i in L]
A

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 8.82 µs


In [8]:
n = 1000000
L = np.arange(n)
L

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [9]:
%%time
L*2

CPU times: user 3.19 ms, sys: 2.97 ms, total: 6.16 ms
Wall time: 5.67 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [10]:
%%time
A = []
for e in L:
    A.append(e*2)

CPU times: user 355 ms, sys: 14.7 ms, total: 369 ms
Wall time: 369 ms


In [11]:
%%time
A = [i*2 for i in L]

CPU times: user 270 ms, sys: 17.2 ms, total: 287 ms
Wall time: 287 ms


### Universal Function

In [12]:
X = np.arange(1,16).reshape(3, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [14]:
X -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [16]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [18]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [21]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [17]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [19]:
1 /X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [22]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [24]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [25]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [26]:
X / 0

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [27]:
np.arctan(X)

array([[0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077],
       [1.40564765, 1.42889927, 1.44644133, 1.46013911, 1.47112767],
       [1.48013644, 1.48765509, 1.49402444, 1.49948886, 1.50422816]])

In [28]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [29]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [30]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [31]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

# 矩阵之间的运算

In [32]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [34]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [35]:
A + B

array([[10, 11],
       [12, 13]])

In [36]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
# 点乘
A * B

array([[ 0, 10],
       [20, 30]])

In [38]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [39]:
# 转置
A.T

array([[0, 2],
       [1, 3]])

In [41]:
C = np.full((3, 3), 666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [42]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [44]:
v = np.array([1, 2])
v

array([1, 2])

In [45]:
A

array([[0, 1],
       [2, 3]])

In [46]:
v + A

array([[1, 3],
       [3, 5]])

In [47]:
# broadcast 

In [48]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [49]:
np.tile(v,(1,2))

array([[1, 2, 1, 2]])

In [50]:
np.tile(v,(2,1))+A

array([[1, 3],
       [3, 5]])

In [51]:
np.tile(v,(2,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [52]:
v * A

array([[0, 2],
       [2, 6]])

In [53]:
v.dot(A)

array([4, 7])

In [54]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [55]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [56]:
invA = np.linalg.inv(A)

In [57]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [58]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [59]:
X = np.arange(16).reshape(2, 8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [60]:
invX = np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

DSADSA